Logout a user/interpretor
CodeYourFuture/scot-broca-translators pull request #18
Opened 2019-08-24 11:23 UTC by Blaiselubuma

This is just the first step for Logout. I need to make sure that I am on the right track

2019-08-26 18:42 UTC, llh1 requested changes

2019-08-26 18:42 UTC, llh1 commented on client/package.json
> +    "react-router-bootstrap": "^0.25.0",
I don't think you need this library here, we don't use bootstrap in the project too, so this can be removed i think.

2019-08-26 18:42 UTC, llh1 commented on client/src/components/Logout.js
> +class Logout extends Component {
This component is probably not needed anymore, so this file can be removed as well.

2019-08-26 18:42 UTC, llh1 commented on client/src/index.js
> +import Logout from "./components/Logout";
You don't need the Logout component here.

2019-08-26 18:45 UTC, llh1 requested changes

2019-08-26 18:45 UTC, llh1 commented on client/src/index.js
> +            name="editorials"
name props can be removed i think.

2019-08-26 18:49 UTC, Blaiselubuma commented on client/src/index.js
> +            name="editorials"
Done. I've removed these

2019-08-28 17:29 UTC, llh1 approved these changes

2019-08-28 17:29 UTC, merged