Add Validation Api Task 1 and 3
CodeYourFuture/scot-broca-translators pull request #41
Opened 2019-09-11 18:47 UTC by Blaiselubuma

2019-09-11 20:25 UTC, llh1 requested changes

2019-09-11 20:25 UTC, llh1 commented on server/api/documents.js
> +      res.status(400).send("Some mandatory field is missing");
You will need to use the keyword `return` before res.status... otherwise the execution will continue.

2019-09-11 20:25 UTC, llh1 commented on server/services/database/documents.js
> +    content;
You have syntax problem here, if you try your code, it will probably fail.

2019-09-11 20:25 UTC, llh1 commented on server/services/database/documents.js
> +    .catch(e => console.error(e));
You should not catch error and silently print them in the console. Don't catch the error here, you can catch it in the implementation of your route and return an error and a 400 status code.

2019-09-11 20:26 UTC, llh1 requested changes

2019-09-11 20:26 UTC, llh1 commented on server/api/documents.js
> +    } else if (document.due_date === null || document.due_date === "") {
You should also verify the date format, it should follow the pattern YYYY-MM-DD

2019-09-11 20:26 UTC, llh1 commented on server/api/documents.js
> +    } else if (document.due_content === null || document.content === "") {
What is due_content? i think it's content right?

2019-09-12 12:03 UTC, Blaiselubuma commented on server/api/documents.js
> +    } else if (document.due_date === null || document.due_date === "") {
How to do to verify the date format ? Need help

2019-09-12 12:03 UTC, Blaiselubuma commented on server/api/documents.js
> +      res.status(400).send("Some mandatory field is missing");
Done

2019-09-12 12:04 UTC, Blaiselubuma commented on server/api/documents.js
> +    } else if (document.due_content === null || document.content === "") {
Done

2019-09-12 12:05 UTC, Blaiselubuma commented on server/services/database/documents.js
> +    content;
I didn't write these codes. Anyway, could you give me a clue please ?

2019-09-12 12:06 UTC, Blaiselubuma commented on server/services/database/documents.js
> +    .catch(e => console.error(e));
Neither these ones ...But I can work on it, however an help is welcome

2019-09-12 12:13 UTC, llh1 requested changes

2019-09-12 12:13 UTC, llh1 commented on server/api/documents.js
> +    } else if (document.due_date === null || document.due_date === "") {
Try something like this: https://stackoverflow.com/questions/7388001/javascript-regex-to-validate-date-format :)

2019-09-12 12:13 UTC, llh1 commented on server/services/database/documents.js
> +    content;
You need to write a valid JS function, this syntax is not javascript. Check how it was written before your changes :) All of these are paremeters of the function.

2019-09-14 13:36 UTC, llh1 approved these changes

2019-09-14 13:36 UTC, merged