Use the API endpoint to store a new document when submitting the create document form
CodeYourFuture/scot-broca-translators pull request #43
Opened 2019-09-11 21:29 UTC by hackermariama

2019-09-12 21:27 UTC, llh1 requested changes

2019-09-12 21:27 UTC, llh1 commented on client/src/api/documents.js
> +    .then(this.handleErrors)
This will not work as this.handleErrors is not defined here.

2019-09-12 21:27 UTC, llh1 commented on client/src/api/documents.js
> +    .then(this.resetForm)
This will not work as this.resetForm is not defined here.

2019-09-12 21:27 UTC, llh1 commented on client/src/api/documents.js
> +      this.setState({
You can only use setState inside a React component. You need to do all of this in a React component.

2019-09-14 12:25 UTC, hackermariama commented on client/src/api/documents.js
> +    .then(this.handleErrors)
its defined now

2019-09-14 12:26 UTC, hackermariama commented on client/src/api/documents.js
> +    .then(this.resetForm)
its fixed now

2019-09-14 12:26 UTC, hackermariama commented on client/src/api/documents.js
> +      this.setState({
done

2019-09-14 14:33 UTC, llh1 approved these changes

2019-09-14 14:34 UTC, merged